# Docker Compose description of the combined application.
# 'docker-compose up' will run this.

version: '3'

services:

  mongodb:
    container_name: mongodb_poo
    image: mongo:4.4.0
    restart: always
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: mongodb_test_poo
    ports:
      # The standard AMQP protocol port
      - '27017:27017'
    networks:
      - mongo-network

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    environment:
      # Credentials for links in containers
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb_poo
      # HTTP username and password
      - ME_CONFIG_BASICAUTH_USERNAME=dev
      - ME_CONFIG_BASICAUTH_PASSWORD=dev
    ports:
      # HTTP port management UI
      - 8081:8081
    networks:
      - mongo-network

volumes:


networks:
  mongo-network:
    driver: bridge